{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pgha.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgha.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pgha.selectorLabels" . | nindent 6 }}
      postgres-ha/metrics: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
    {{- if .Values.metrics.exporters.enabled }}
    - port: exporter
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
    {{- end }}
{{- if and .Values.pgbouncer.enabled .Values.metrics.exporters.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pgha.pgbouncer" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgha.labels" . | nindent 4 }}
    postgres-ha/metrics: pgbouncer
spec:
  selector:
    {{- include "pgha.pgbouncerSelectorLabels" . | nindent 4 }}
  ports:
    - name: exporter
      port: 9127
      targetPort: exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "pgha.pgbouncer" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pgha.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "pgha.selectorLabels" . | nindent 6 }}
      postgres-ha/metrics: pgbouncer
  endpoints:
    - port: exporter
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
{{- end }}
